### ISSUE TITLE
crash when placing robot crate

### ISSUE THREAD

**Issue by lag42** [The-Fireplace/Mechanical-Soldiers#1]
if it matters it had a copper-redstone cpu, wooden body and bronze joints
https://pastebin.com/mBxDqgEi

**Comment by The-Fireplace** [comment]
Thanks for reporting, I'll fix it ASAP.

**Comment by The-Fireplace** [comment]
Fixed in 1.0.2

**Comment by FireStorm-Gaming** [comment]
still not fixed for me
