### ISSUE TITLE
Crash with NEI for 1.12.1

### ISSUE THREAD

**Issue by brisingraerowing** [The-Fireplace/Mechanical-Soldiers#11]
I have NEI for 1.12.1 and tried to use the delete item button, and crashed when moving an item over it.

[Crash Log](https://gist.github.com/BrisingrAerowing/0b2df0a7e7780d133ddd12e375e3ed0d)

It seems that a sanity check needs to be done on the input to the event.

**Comment by The-Fireplace** [comment]
Not my fault, it's CCL's for allowing null ItemStacks. The author of CCL just fixed this earlier today, so you may want to see about updating that.
