### ISSUE TITLE
[Enhancement] Support casting robot parts with tinker's construct's smeltery.

### ISSUE THREAD

**Issue by YaibaToKen** [The-Fireplace/Mechanical-Soldiers#26]
Pretty much what it says in the tin xD

**Comment by The-Fireplace** [comment]
I'm pretty sure I already did that, for the metals this mod supports.

**Comment by YaibaToKen** [comment]
ohh, didn't notice, apologies. Could I ask for support for the remainder of tinker's metals?

**Comment by The-Fireplace** [comment]
As much as I'd love to, it would probably require a rewrite of most of the
mod to depend on Tinkers, to make it support the sheer number of metals
that can be used with Tinkers. If I were to do this, I would want to try to
make it support metals from Tinkers add-ons as well. I might be able to
make an add on that can do it one day, but for now, my answer is no.
