### ISSUE TITLE
Robot section of guide missing still

### ISSUE THREAD

**Issue by MoonlightSystem** [The-Fireplace/Mechanical-Soldiers#3]
In the 1.0.2 version, it still doesn't show up

**Comment by The-Fireplace** [comment]
Will you provide your fml-client-latest.log?

**Comment by MoonlightSystem** [comment]
https://hastebin.com/upikosoret.md

**Comment by The-Fireplace** [comment]
Alright. Working on it. I have to fix TeamAmeriFrance/Guide-API#81 first

**Comment by The-Fireplace** [comment]
Fixed in 1.0.3
