### ISSUE TITLE
[1.12.2] Skeletons won't attack anything?

### ISSUE THREAD

**Issue by phantasmuh** [The-Fireplace/Mechanical-Soldiers#31]
Hi, I was using this mod (I really liked the idea a lot) and made some robots when I notice that most of them aren't even attacking anything. I reset their actions and commands but nothing worked. I deleted them, and spawned in some new ones, but only a couple out of the bunches of 9 I spawned in actually went and attacked hostile mobs. I can't seem to figure out what's happening. No errors or anything show up in the logs. I even installed the MobBattleMod to try and force the skeletons to fight, but they just sit there idle. Am I missing something? (no, not a cpu, I already have them)

EDIT: By the way, I'd love to have an interface that shows the current progress of the skeletons being built. Sure, there's one in WAILA, but I need to fly away and unload the chunks for it to update :/ I'd appreciate it! thanks!

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, if I update this mod it will be rewritten and only support Fabric going forward. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
