### ISSUE TITLE
game crashes whenever i render a previously-loaded world using the latest mod version and latest recommended forge version

### ISSUE THREAD

**Issue by LordDecay26** [The-Fireplace/Mechanical-Soldiers#8]
i got a crash when attempting to look at what i believe to be the Blueprints in a dungeon chest, it had a missing texture. so i assumed it was my forge version. i then updated to the latest recommended forge version and now i cannot even load the world itself without crashing.

**Comment by The-Fireplace** [comment]
Will you provide the crash report, and your fml-client-latest.log?

**Comment by The-Fireplace** [comment]
And what Minecraft version and mod version?

**Comment by LordDecay26** [comment]
it did not give me a crash report. it just said something along the lines of "your game has crashed, sorry for the inconvenience"  i am using forge version 13.20.1.2386

**Comment by MoonlightSystem** [comment]
If it crashed there is a crash report in a the folder called "crash-reports", look for the latest one

**Comment by LordDecay26** [comment]
okay well if i knew that this problem would be fixed a long time ago, thanks. i think i know how to fix the problem, the the thing is being real buggy right now though, not entirely sure why. and the crash report is just weird.

**Comment by LordDecay26** [comment]
looks like i have to re-install all of my mods
